import {fetchSystemSettings,getRestaurantLogoUrl,persistSystemSettings,uploadRestaurantLogo} from '../repositories/systemSettings.repository';
import type {SystemSettings} from '../types/systemSettings';
import {validateLogoFile,validateSystemSettings} from '../utils/systemSettings.validation';
const camel=(row:Record<string,unknown>):SystemSettings=>({revision:Number(row.revision),canEdit:Boolean(row.canEdit),restaurantInfo:(row.restaurant_info||{}) as SystemSettings['restaurantInfo'],logoPath:String(row.logo_path||''),logoUrl:getRestaurantLogoUrl(String(row.logo_path||'')),taxEnabled:Boolean(row.tax_enabled),taxName:String(row.tax_name),taxRate:Number(row.tax_rate),taxMode:row.tax_mode as SystemSettings['taxMode'],serviceChargeEnabled:Boolean(row.service_charge_enabled),serviceChargeName:String(row.service_charge_name),serviceChargeRate:Number(row.service_charge_rate),serviceChargeOrderTypes:row.service_charge_order_types as string[],receiptConfig:row.receipt_config as Record<string,unknown>,timezone:String(row.timezone),currencyCode:String(row.currency_code),currencySymbol:String(row.currency_symbol),decimalPlaces:Number(row.decimal_places),roundingRule:String(row.rounding_rule),defaultLanguage:row.default_language as SystemSettings['defaultLanguage'],enabledLanguages:row.enabled_languages as SystemSettings['enabledLanguages'],backupConfig:row.backup_config as Record<string,unknown>,printers:((row.printers||[]) as Record<string,unknown>[]).map(p=>({id:String(p.id),name:String(p.name),type:p.type as SystemSettings['printers'][number]['type'],connectionType:p.connection_type as SystemSettings['printers'][number]['connectionType'],ipAddress:String(p.ip_address||''),port:String(p.port||''),paperWidth:Number(p.paper_width) as 58|80,autoCut:Boolean(p.auto_cut),copies:Number(p.copies),enabled:Boolean(p.enabled)})),stations:((row.stations||[]) as Record<string,unknown>[]).map(s=>({id:String(s.id),name:String(s.name),code:String(s.code),stationType:s.station_type as SystemSettings['stations'][number]['stationType'],printerId:String(s.printer_id||''),kdsDeviceKey:String(s.kds_device_key||''),categoryIds:(s.categoryIds||[]) as string[],enabled:Boolean(s.enabled)})),numbering:((row.numbering||[]) as Record<string,unknown>[]).map(n=>({entityCode:n.entity_code as SystemSettings['numbering'][number]['entityCode'],prefix:String(n.prefix),sequencePadding:Number(n.sequence_padding),dateFormat:n.date_format as SystemSettings['numbering'][number]['dateFormat'],resetFrequency:n.reset_frequency as SystemSettings['numbering'][number]['resetFrequency']})),integrations:((row.integrations||[]) as Record<string,unknown>[]).map(i=>({integrationType:String(i.integration_type),provider:String(i.provider||''),enabled:Boolean(i.enabled),status:i.status as SystemSettings['integrations'][number]['status'],publicConfig:(i.public_config||{}) as Record<string,unknown>,credentialsConfigured:Boolean(i.credentials_configured)})),categories:(row.categories||[]) as SystemSettings['categories']});
export async function getSystemSettings(){const result=await fetchSystemSettings();return{data:result.data?camel(result.data as Record<string,unknown>):null,error:result.error};}
const payload=(s:SystemSettings)=>({restaurantInfo:s.restaurantInfo,logoPath:s.logoPath,taxEnabled:s.taxEnabled,taxName:s.taxName,taxRate:s.taxRate,taxMode:s.taxMode,serviceChargeEnabled:s.serviceChargeEnabled,serviceChargeName:s.serviceChargeName,serviceChargeRate:s.serviceChargeRate,serviceChargeOrderTypes:s.serviceChargeOrderTypes,receiptConfig:s.receiptConfig,timezone:s.timezone,currencyCode:s.currencyCode,currencySymbol:s.currencySymbol,decimalPlaces:s.decimalPlaces,roundingRule:s.roundingRule,defaultLanguage:s.defaultLanguage,enabledLanguages:s.enabledLanguages,backupConfig:s.backupConfig,printers:s.printers,stations:s.stations,numbering:s.numbering,integrations:s.integrations});
export async function saveSystemSettings(settings:SystemSettings){const errors=validateSystemSettings(settings);if(errors.length)return{data:null,error:new Error(errors.join(' '))};const result=await persistSystemSettings(payload(settings),settings.revision);return{data:result.data?camel(result.data as Record<string,unknown>):null,error:result.error};}
export async function uploadSystemLogo(file:File){const error=validateLogoFile(file);if(error)return{data:null,error:new Error(error)};return uploadRestaurantLogo(file);}
export function testPrinterConfiguration(printer:SystemSettings['printers'][number]){if(!printer.enabled)return{status:'INVALID_CONFIGURATION',message:'Printer is disabled.'};if(printer.connectionType!=='SYSTEM_PRINT')return{status:'UNKNOWN',message:'Browser clients cannot safely verify this printer connection.'};return{status:'UNKNOWN',message:'The system print dialog can be opened, but physical completion cannot be verified.'};}
export function testIntegrationConfiguration(integration:SystemSettings['integrations'][number]){if(!integration.credentialsConfigured)return{status:'NOT_CONFIGURED',message:'Credentials must be configured in the server environment.'};return{status:'UNKNOWN',message:'No provider-specific health adapter is installed.'};}
