import { buildReportSummary } from '../utils/reportSummary.js';

function safeName(value) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }
function excelValue(value, type) {
  if (value == null || value === '') return null;
  if (type === 'percent') return Number(value) / 100;
  if (['currency','number'].includes(type)) return Number(value);
  if (type === 'date' || type === 'datetime') return new Date(type === 'date' ? `${String(value).slice(0,10)}T00:00:00` : value);
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

export async function buildReportWorkbook(report, rows) {
  const excelModule = await import('exceljs');
  const Excel = excelModule.default || excelModule;
  const workbook = new Excel.Workbook();
  workbook.creator = 'Restaurant POS System'; workbook.created = new Date(report.generatedAt);
  const summary = workbook.addWorksheet('Summary');
  summary.addRows([['Report', report.definition.title],['Period', `${report.dateFrom} to ${report.dateTo}`],['Search', report.appliedFilters?.search || 'All records'],['Sort', report.appliedFilters?.sortKey ? `${report.appliedFilters.sortKey} ${report.appliedFilters.sortDirection}` : 'Default'],['Generated By', report.generatedBy],['Generated At', new Date(report.generatedAt)]]);
  summary.getColumn(1).width = 24; summary.getColumn(2).width = 32;
  summary.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; summary.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF121212' } };
  summary.addRow([]); summary.addRow(['Summary', 'Value']);
  buildReportSummary(report.reportId, rows, report.summary).forEach(item => { const row = summary.addRow([item.label, item.value]); if (item.type === 'currency') row.getCell(2).numFmt = 'RM #,##0.00;[Red]-RM #,##0.00'; });
  const details = workbook.addWorksheet('Details', { views: [{ state: 'frozen', ySplit: 1 }] });
  details.columns = report.definition.columns.map(column => ({ header: column.label, key: column.key, width: Math.min(40, Math.max(12, column.label.length + 3)) }));
  rows.forEach(source => {
    const row = details.addRow(Object.fromEntries(report.definition.columns.map(column => [column.key, excelValue(source[column.key], column.type)])));
    report.definition.columns.forEach((column, index) => {
      const cell = row.getCell(index + 1);
      if (column.type === 'currency') cell.numFmt = 'RM #,##0.00;[Red]-RM #,##0.00';
      if (column.type === 'percent') cell.numFmt = '0.00%';
      if (column.type === 'date') cell.numFmt = 'dd/mm/yyyy';
      if (column.type === 'datetime') cell.numFmt = 'dd/mm/yyyy hh:mm';
    });
  });
  details.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: report.definition.columns.length } };
  details.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; details.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF121212' } };
  return workbook;
}

export async function exportReportExcel(report, rows) {
  const workbook = await buildReportWorkbook(report, rows);
  const buffer = await workbook.xlsx.writeBuffer();
  const url = URL.createObjectURL(new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${safeName(report.definition.title)}-${report.dateFrom}-${report.dateTo}.xlsx`; anchor.click(); URL.revokeObjectURL(url);
}
