import { formatReportValue } from '../utils/reportFormatters.js';
import { buildReportSummary } from '../utils/reportSummary.js';

function safeName(value) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); }

export async function buildReportPdf(report, rows) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const doc = new jsPDF({ orientation: report.definition.orientation, unit: 'mm', format: 'a4' });
  doc.setFontSize(15); doc.setFont(undefined, 'bold'); doc.text('RESTAURANT POS SYSTEM', 14, 14);
  doc.setFontSize(12); doc.text(report.definition.title.toUpperCase(), 14, 21);
  doc.setFont(undefined, 'normal'); doc.setFontSize(8);
  doc.text(`Period: ${report.dateFrom} to ${report.dateTo}`, 14, 27);
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString('en-MY')}  |  By: ${report.generatedBy}`, 14, 32);
  doc.text(`Filters: search=${report.appliedFilters?.search || 'all'}; sort=${report.appliedFilters?.sortKey || 'default'} ${report.appliedFilters?.sortDirection || ''}`, 14, 36);
  const summaryText = buildReportSummary(report.reportId, rows, report.summary).map(item => `${item.label}: ${formatReportValue(item.value, item.type)}`).join('   |   ');
  const wrapped = doc.splitTextToSize(summaryText, doc.internal.pageSize.getWidth() - 28); doc.text(wrapped, 14, 41);
  autoTable(doc, { startY: 42 + wrapped.length * 4, head: [report.definition.columns.map(column => column.label)], body: rows.map(row => report.definition.columns.map(column => formatReportValue(row[column.key], column.type))), styles: { fontSize: report.definition.orientation === 'landscape' ? 5.5 : 7, cellPadding: 1.4, overflow: 'linebreak' }, headStyles: { fillColor: [18,18,18], textColor: [212,175,55] }, didDrawPage: () => { const height = doc.internal.pageSize.getHeight(); doc.setFontSize(7); doc.setTextColor(100); doc.text(`Generated by POS System · ${new Date(report.generatedAt).toLocaleString('en-MY')}`, 14, height - 7); } });
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) { doc.setPage(page); doc.setFontSize(7); doc.setTextColor(100); doc.text(`Page ${page} of ${pageCount}`, doc.internal.pageSize.getWidth() - 30, doc.internal.pageSize.getHeight() - 7); }
  return doc;
}

export async function exportReportPdf(report, rows) {
  const doc = await buildReportPdf(report, rows);
  doc.save(`${safeName(report.definition.title)}-${report.dateFrom}-${report.dateTo}.pdf`);
}
