const money = (key, label) => ({ key, label, type: 'currency' });
const number = (key, label) => ({ key, label, type: 'number' });
const text = (key, label) => ({ key, label, type: 'text' });
const date = (key, label) => ({ key, label, type: 'date' });
const dateTime = (key, label) => ({ key, label, type: 'datetime' });
const percent = (key, label) => ({ key, label, type: 'percent' });

export const REPORT_GROUPS = [
  { id: 'sales', label: 'Sales', reports: ['daily-sales', 'hourly-sales'] },
  { id: 'orders', label: 'Orders', reports: ['order-transactions', 'cancellations', 'refunds'] },
  { id: 'products', label: 'Products', reports: ['product-sales', 'category-sales'] },
  { id: 'payments', label: 'Payments', reports: ['payments'] },
  { id: 'operations', label: 'Operations', reports: ['staff-sales', 'kitchen-performance'] },
];

export const REPORT_DEFINITIONS = {
  'daily-sales': { title: 'Daily Sales Report', group: 'sales', orientation: 'landscape', search: ['order_number','payment_number','payment_method'], columns: [date('report_date','Business Date'),text('payment_number','Payment No'),text('order_number','Order No'),text('payment_method','Method'),text('dining_mode','Order Type'),money('subtotal','Gross'),money('discount','Discount'),money('tax','Tax'),money('service_charge','Service Charge'),money('order_total','Order Total'),money('amount_paid','Collected'),dateTime('paid_at','Paid At')] },
  'order-transactions': { title: 'Order Transaction Report', group: 'orders', orientation: 'landscape', search: ['order_number','table_number','staff_name','payment_method'], columns: [text('order_number','Order No'),date('business_date','Business Date'),dateTime('order_date_time','Order Date / Time'),text('order_type','Order Type'),text('table_number','Table No'),number('guest_count','Guests'),text('staff_name','Staff / Waiter'),money('subtotal','Subtotal'),money('discount','Discount'),money('tax','Tax'),money('service_charge','Service Charge'),money('grand_total','Grand Total'),text('payment_method','Payment Method'),text('payment_status','Payment Status'),text('order_status','Order Status'),dateTime('completed_at','Completed At')] },
  payments: { title: 'Payment Transaction Report', group: 'payments', orientation: 'landscape', search: ['payment_number','order_number','receipt_number','transaction_reference','cashier','confirmed_by','provider_name','provider_id'], columns: [text('payment_number','Payment No'),text('order_number','Order No'),text('receipt_number','Receipt No'),dateTime('payment_at','Payment Date / Time'),text('payment_method','Method'),text('provider_name','Provider'),text('provider_id','Provider ID'),text('qr_scheme','QR Scheme'),text('qr_mode','QR Mode'),money('payment_amount','Amount'),text('payment_status','Status'),text('transaction_reference','Reference'),text('cashier','Cashier'),text('confirmed_by','Confirmed By'),dateTime('confirmed_at','Confirmed At'),text('confirmation_mode','Confirmation'),money('refunded_amount','Refunded')] },
  'product-sales': { title: 'Product Sales Report', group: 'products', orientation: 'landscape', search: ['product_code','product_name','category_name'], columns: [text('product_code','Product Code'),text('product_name','Product Name'),text('category_name','Category'),number('quantity_sold','Quantity Sold'),number('order_count','Order Count'),money('gross_sales','Gross Sales'),money('discount_allocated','Discount Allocated'),money('net_sales','Net Sales'),money('average_unit_price','Average Price'),percent('sales_contribution','Contribution')] },
  'category-sales': { title: 'Category Sales Report', group: 'products', orientation: 'landscape', search: ['category_code','category_name'], columns: [text('category_code','Category Code'),text('category_name','Category Name'),number('quantity_sold','Quantity Sold'),number('order_count','Order Count'),money('gross_sales','Gross Sales'),money('discount','Discount'),money('net_sales','Net Sales'),percent('sales_percentage','Sales %')] },
  cancellations: { title: 'Cancellation / Void Report', group: 'orders', orientation: 'landscape', search: ['order_number','product','reason','cancelled_by'], columns: [text('order_number','Order No'),text('order_item_line','Item Line'),text('product','Product'),number('quantity','Quantity'),money('original_amount','Original Amount'),money('cancelled_amount','Cancelled Amount'),text('cancellation_type','Type'),text('reason','Reason'),text('cancelled_by','Cancelled By'),text('cancelled_by_role','Role'),text('approved_by','Approved By'),dateTime('changed_at','Cancelled At')] },
  refunds: { title: 'Refund Report', group: 'orders', orientation: 'landscape', search: ['refund_number','original_payment_number','order_number','receipt_number','reason','requested_by'], columns: [text('refund_number','Refund No'),text('original_payment_number','Payment No'),text('order_number','Order No'),text('receipt_number','Receipt No'),money('original_payment_amount','Original Payment'),money('refund_amount','Refund Amount'),text('refund_method','Method'),text('refund_type','Type'),text('reason','Reason'),text('requested_by','Requested By'),text('approved_by','Approved By'),dateTime('refunded_at','Refunded At')] },
  'staff-sales': { title: 'Staff Sales Report', group: 'operations', orientation: 'landscape', search: ['staff_name','role'], columns: [text('user_id','Staff ID'),text('staff_name','Staff Name'),text('role','Role'),number('orders_created','Orders Created'),number('total_orders','Orders Completed'),number('items_sold','Items Sold'),money('gross_sales','Gross Sales'),money('net_sales','Net Sales'),money('average_order_value','Average Order'),number('cancelled_orders','Cancelled'),number('void_items','Void Items'),money('discount_given','Discount'),number('refund_count','Refunds')] },
  'hourly-sales': { title: 'Hourly Sales Report', group: 'sales', orientation: 'portrait', search: ['hour_slot'], columns: [date('business_date','Business Date'),text('hour_slot','Hour Slot'),number('order_count','Orders'),number('guest_count','Guests'),number('quantity_sold','Quantity'),money('net_sales','Net Sales'),money('average_order_value','Average Order')] },
  'kitchen-performance': { title: 'Kitchen Performance Report', group: 'operations', orientation: 'landscape', search: ['kds_number','order_number','order_type','table_number','kitchen_status'], columns: [text('kds_number','KDS No'),text('order_number','Order No'),text('order_type','Order Type'),text('table_number','Table No'),dateTime('submitted_at','Submitted'),dateTime('preparing_at','Preparing'),dateTime('ready_at','Ready'),dateTime('served_at','Served'),number('preparation_minutes','Prep Min'),number('waiting_minutes','Wait Min'),number('fulfilment_minutes','Total Min'),text('kitchen_status','Status'),text('delay_flag','Delayed')] },
};

export const reportDefinition = (id) => REPORT_DEFINITIONS[id] || REPORT_DEFINITIONS['daily-sales'];
