import React, { useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Banknote, BarChart3, CalendarDays, CheckCircle2, CircleX,
  Clock3, CreditCard, ExternalLink, QrCode, ReceiptText, RefreshCw, ShoppingBag,
  Sparkles, Table2, TrendingUp, Utensils, WalletCards,
} from 'lucide-react';
import { useAdminDashboard } from '../../hooks/useAdminDashboard';
import { formatCurrency, formatDate, formatDateTime, formatNumber, formatTime, humanizeCode } from '../../utils/admin-dashboard-formatters';
import DashboardFilters from './dashboard/DashboardFilters';
import { DashboardSkeleton, EmptyState, ErrorState, MetricCard, Panel, StatusBadge } from './dashboard/DashboardPrimitives';

const paymentIcons={CASH:Banknote,QR:QrCode,CARD:CreditCard,EWALLET:WalletCards};

function SalesPerformance({ data, state }) {
  const rows=data.salesPerformance||[];
  const metric=state.filters.metric;
  const valueOf=row=>metric==='orders'?Number(row.order_count||0):metric==='averageOrderValue'?Number(row.average_order_value||0):Number(row.revenue||0);
  const max=Math.max(1,...rows.map(valueOf));
  const format=metric==='orders'?formatNumber:formatCurrency;
  return <Panel title="Sales Performance" subtitle="Recognised when an order is fully settled; refunds appear in the period they occur." className="xl:col-span-2" action={<div className="flex gap-2"><select aria-label="Chart metric" value={metric} onChange={e=>state.setFilter('metric',e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs"><option value="revenue">Revenue</option><option value="orders">Order count</option><option value="averageOrderValue">Average order value</option></select><select aria-label="Chart interval" value={state.filters.granularity} onChange={e=>state.setFilter('granularity',e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs"><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></div>}>
    {rows.length?<div className="mt-6"><div className="flex h-56 items-end gap-2 border-b border-slate-200 px-2">{rows.map((row,index)=><div key={`${row.bucket}-${index}`} className="group relative flex h-full min-w-0 flex-1 items-end"><div title={`${row.bucket}: ${format(valueOf(row))}`} className="w-full rounded-t-lg bg-gradient-to-t from-amber-500 to-amber-300 transition hover:from-amber-600" style={{height:`${Math.max(5,valueOf(row)/max*100)}%`}}/><span className="pointer-events-none absolute -top-1 left-1/2 z-10 hidden -translate-x-1/2 whitespace-nowrap rounded bg-slate-950 px-2 py-1 text-[10px] text-white group-hover:block">{format(valueOf(row))}</span></div>)}</div><div className="mt-2 flex gap-2 px-2">{rows.map((row,index)=><span key={`${row.bucket}-label-${index}`} className="min-w-0 flex-1 truncate text-center text-[10px] text-slate-400">{String(row.bucket).slice(5)}</span>)}</div><p className="mt-4 text-xs text-slate-400">Current period shown. KPI comparison uses the immediately preceding equivalent period.</p></div>:<EmptyState/>}
  </Panel>;
}

function PaymentOverview({ data, navigate }) {
  const summary=data.payments||{};const methods=summary.methods||[];const lookup=new Map(methods.map(item=>[item.payment_method,item]));const max=Math.max(1,...methods.map(item=>Number(item.amount||0)));
  return <Panel title="Payment Overview" subtitle="Successful and historically refunded transactions; failures never enter sales totals.">
    <div className="mt-5 space-y-4">{['CASH','QR','CARD','EWALLET'].map(method=>{const item=lookup.get(method)||{};const Icon=paymentIcons[method];return <button key={method} onClick={()=>navigate('payments',{method})} className="block w-full text-left"><div className="mb-1 flex items-center justify-between text-xs"><span className="flex items-center gap-2 font-bold text-slate-600"><Icon size={15}/>{method==='EWALLET'?'E-Wallet':method}</span><strong>{formatCurrency(item.amount)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-400" style={{width:`${Number(item.amount||0)/max*100}%`}}/></div><p className="mt-1 text-[10px] text-slate-400">{formatNumber(item.transaction_count)} transactions</p></button>})}</div>
    <div className="mt-5 grid grid-cols-3 gap-2 border-t pt-4 text-center"><button onClick={()=>navigate('payments',{status:'REFUNDED'})} className="rounded-lg bg-amber-50 p-2"><strong className="block text-sm text-amber-800">{formatCurrency(summary.refunds?.amount)}</strong><span className="text-[10px] text-amber-700">{formatNumber(summary.refunds?.count)} refunds</span></button><button onClick={()=>navigate('payments',{status:'FAILED'})} className="rounded-lg bg-red-50 p-2"><strong className="block text-sm text-red-700">{formatNumber(summary.failed?.count)}</strong><span className="text-[10px] text-red-600">Failed payments</span></button><button onClick={()=>navigate('orders',{paymentStatus:'UNPAID'})} className="rounded-lg bg-slate-100 p-2"><strong className="block text-sm">{formatNumber(summary.unpaidOrders)}</strong><span className="text-[10px] text-slate-500">Unpaid orders</span></button></div>
  </Panel>;
}

function OrderOverview({ data, navigate }) {
  const summary=data.orders||{};const statuses=data.orderStatus||{};const types=data.orderTypes||{};const total=Math.max(1,Number(summary.total||0));
  const statusCards=[['PLACED',ShoppingBag],['CONFIRMED, PREPARING',Utensils],['READY',Sparkles],['SERVED',WalletCards],['COMPLETED',CheckCircle2],['CANCELLED',CircleX]];
  return <Panel title="Order Overview" subtitle="Orders created in the selected period.">
    <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><button onClick={()=>navigate('orders',{})} className="rounded-xl bg-slate-950 p-3 text-left text-white"><span className="text-[10px] uppercase text-slate-400">Total</span><strong className="mt-1 block text-xl">{formatNumber(summary.total)}</strong></button><button onClick={()=>navigate('orders',{})} className="rounded-xl bg-sky-50 p-3 text-left"><span className="text-[10px] uppercase text-sky-600">Open</span><strong className="mt-1 block text-xl">{formatNumber(summary.open)}</strong></button><button onClick={()=>navigate('orders',{status:'COMPLETED'})} className="rounded-xl bg-emerald-50 p-3 text-left"><span className="text-[10px] uppercase text-emerald-600">Completed</span><strong className="mt-1 block text-xl">{formatNumber(summary.completed)}</strong></button><button onClick={()=>navigate('orders',{status:'CANCELLED'})} className="rounded-xl bg-red-50 p-3 text-left"><span className="text-[10px] uppercase text-red-600">Cancelled</span><strong className="mt-1 block text-xl">{formatNumber(summary.cancelled)}</strong></button></div>
    <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{statusCards.map(([label,Icon])=>{const codes=label.split(', ');const value=codes.reduce((sum,code)=>sum+Number(statuses[code]||0),0);return <button key={label} onClick={()=>navigate('orders',codes.length===1?{status:codes[0]}:{})} className="flex items-center justify-between rounded-lg border p-2 text-xs hover:border-amber-300"><span className="flex items-center gap-2 text-slate-500"><Icon size={14}/>{label}</span><strong>{value}</strong></button>})}</div>
    <div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span>Dine-in {formatNumber(types.dineIn)}</span><span>Takeaway {formatNumber(types.takeaway)}</span></div><div className="flex h-3 overflow-hidden rounded-full bg-slate-100"><div className="bg-sky-500" style={{width:`${Number(types.dineIn||0)/total*100}%`}}/><div className="bg-violet-400" style={{width:`${Number(types.takeaway||0)/total*100}%`}}/></div></div>
  </Panel>;
}

function LiveOperations({ data, navigate }) {
  const tables=data.live?.tables||{};const kitchen=data.live?.kitchen||{};
  const items=[...(data.access?.tables?[['Available tables',tables.available,Table2,'emerald',()=>navigate('tables',{status:'AVAILABLE'})],['Occupied tables',tables.occupied,Table2,'sky',()=>navigate('tables',{status:'OCCUPIED'})],['Cleaning tables',tables.cleaning,RefreshCw,'slate',()=>navigate('tables',{status:'CLEANING'})]]:[]),...(data.access?.orders?[['Waiting payment',tables.waitingPayment,WalletCards,'amber',()=>navigate('orders',{paymentStatus:'UNPAID'})],['Kitchen waiting',kitchen.waiting,Clock3,'amber',()=>navigate('orders',{status:'CONFIRMED'})],['Preparing',kitchen.preparing,Utensils,'sky',()=>navigate('orders',{status:'PREPARING'})],['Ready',kitchen.ready,Sparkles,'emerald',()=>navigate('orders',{status:'READY'})],['Delayed',kitchen.delayed,AlertTriangle,'red',()=>navigate('orders',{status:'PREPARING'})]]:[])];
  const colors={emerald:'bg-emerald-50 text-emerald-700',sky:'bg-sky-50 text-sky-700',amber:'bg-amber-50 text-amber-800',slate:'bg-slate-100 text-slate-600',red:'bg-red-50 text-red-700'};
  return <Panel title="Live Operations" subtitle={`Live table and kitchen state · delayed after ${data.delayedOrderMinutes||20} minutes`}>{items.length?<div className="mt-5 grid grid-cols-2 gap-3">{items.map(([label,value,Icon,tone,onClick])=><button key={label} onClick={onClick} className={`rounded-xl p-3 text-left transition hover:-translate-y-0.5 ${colors[tone]}`}><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase">{label}</span><Icon size={15}/></div><strong className="mt-2 block text-xl text-slate-950">{formatNumber(value)}</strong></button>)}</div>:<EmptyState>Live operations require table.view or order.view.</EmptyState>}</Panel>;
}

function TopProducts({ data, navigate }) {
  const [sort,setSort]=useState('quantity');const rows=useMemo(()=>[...(data.topProducts||[])].sort((a,b)=>Number(b[sort]||0)-Number(a[sort]||0)),[data.topProducts,sort]);
  return <Panel title="Top Selling Products" subtitle="Paid sales only; cancelled and voided items excluded." action={<select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs"><option value="quantity">By quantity</option><option value="revenue">By revenue</option></select>}>
    {rows.length?<div className="mt-4 space-y-2">{rows.map((product,index)=><button key={product.product_id} onClick={()=>navigate('products',{productId:product.product_id})} className="grid w-full grid-cols-[28px_1fr_auto] items-center gap-2 rounded-xl p-2 text-left hover:bg-amber-50"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-950 text-xs font-black text-white">{index+1}</span><span className="min-w-0"><strong className="block truncate text-sm">{product.name}</strong><small className="text-slate-400">{formatNumber(product.quantity)} sold</small></span><strong className="text-sm">{formatCurrency(product.revenue)}</strong></button>)}</div>:<EmptyState/>}
    {data.topCategory&&<div className="mt-4 rounded-xl bg-violet-50 p-3"><p className="text-[10px] font-black uppercase text-violet-600">Top category</p><div className="mt-1 flex items-end justify-between"><strong>{data.topCategory.name}</strong><span className="text-sm font-black text-violet-700">{data.topCategory.sales_share_percent}% of sales</span></div></div>}
  </Panel>;
}

function AlertsPanel({ data, navigate }) {
  const go=alert=>{if(alert.destination==='payments')navigate('payments',{status:alert.filter_value});else if(alert.destination==='orders')navigate('orders',{status:alert.filter_value==='UNPAID'?'':alert.filter_value,paymentStatus:alert.filter_value==='UNPAID'?'UNPAID':''});else navigate(alert.destination||'dashboard',{});};
  return <Panel title="Alerts & Attention" subtitle="Prioritised operational exceptions, not a raw event feed.">{data.alerts?.length?<div className="mt-4 max-h-80 space-y-2 overflow-y-auto pr-1">{data.alerts.map((alert,index)=><button key={`${alert.code}-${alert.reference}-${index}`} onClick={()=>go(alert)} className="flex w-full items-start gap-3 rounded-xl border p-3 text-left hover:border-amber-300"><AlertTriangle size={17} className={alert.severity==='CRITICAL'?'mt-0.5 text-red-600':alert.severity==='WARNING'?'mt-0.5 text-amber-600':'mt-0.5 text-sky-600'}/><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><strong className="text-sm">{alert.title}</strong><StatusBadge value={alert.severity}/></span><span className="mt-1 block truncate text-xs text-slate-500">{alert.reference} · {alert.message}</span></span><ExternalLink size={14} className="mt-1 text-slate-300"/></button>)}</div>:<EmptyState>No alerts require attention.</EmptyState>}</Panel>;
}

function RecentOrders({ data, navigate }) { return <Panel title="Recent Orders" subtitle="Latest orders in the selected period." action={<button onClick={()=>navigate('orders',{})} className="flex items-center gap-1 text-xs font-bold text-amber-700">View all <ExternalLink size={13}/></button>} className="overflow-hidden">{data.recentOrders?.length?<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b text-left text-[10px] uppercase tracking-wide text-slate-400">{['Order','Type / Table','Amount','Order Status','Payment','Staff','Time'].map(label=><th key={label} className="px-3 py-2">{label}</th>)}</tr></thead><tbody>{data.recentOrders.map(order=><tr key={order.id} onClick={()=>navigate('orders',{search:order.order_number})} className="cursor-pointer border-b border-slate-100 hover:bg-amber-50"><td className="px-3 py-3 font-bold">{order.order_number}</td><td className="px-3 py-3">{humanizeCode(order.dining_mode)}<small className="ml-2 text-slate-400">{order.table_number||'—'}</small></td><td className="px-3 py-3 font-black">{formatCurrency(order.total)}</td><td className="px-3 py-3"><StatusBadge value={order.status}/></td><td className="px-3 py-3"><StatusBadge value={order.payment_status}/></td><td className="px-3 py-3">{order.staff_name}</td><td className="px-3 py-3 text-xs text-slate-500">{formatTime(order.created_at)}</td></tr>)}</tbody></table></div>:<EmptyState/>}</Panel>; }

function StaffPerformance({ data }) { return <Panel title="Staff Performance" subtitle="Operational aggregates for coaching and planning—not employee surveillance.">{data.staffPerformance?.length?<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-xs"><thead><tr className="border-b text-left uppercase text-slate-400">{['Staff','Orders','Sales','AOV','Refunds','Cancelled','Account'].map(label=><th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{data.staffPerformance.map(staff=><tr key={staff.id} className="border-b border-slate-100"><td className="p-2"><strong className="block text-sm">{staff.name}</strong><span className="text-slate-400">{staff.role}</span></td><td className="p-2 font-bold">{formatNumber(staff.orders_handled)}</td><td className="p-2 font-bold">{formatCurrency(staff.sales_amount)}</td><td className="p-2">{formatCurrency(staff.average_order_value)}</td><td className="p-2">{formatNumber(staff.refund_count)}</td><td className="p-2">{formatNumber(staff.cancellation_count)}</td><td className="p-2"><StatusBadge value={staff.account_status}/></td></tr>)}</tbody></table></div>:<EmptyState/>}</Panel>; }

function RecentActivity({ data, navigate }) { return <Panel title="Recent Activity" subtitle="Append-only audit history; dashboard access is read-only.">{data.recentActivities?.length?<div className="mt-4 space-y-2">{data.recentActivities.map(activity=><button key={activity.id} onClick={()=>navigate('audit',{search:activity.action})} className="flex w-full items-start gap-3 rounded-xl p-2 text-left hover:bg-slate-50"><span className="rounded-full bg-slate-100 p-2 text-slate-500"><Activity size={14}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{humanizeCode(activity.action)}</strong><span className="block truncate text-xs text-slate-400">{activity.actor_name} · {humanizeCode(activity.entity_type)} {activity.entity_id||''}</span></span><time className="text-[10px] text-slate-400">{formatTime(activity.created_at)}</time></button>)}</div>:<EmptyState/>}</Panel>; }

export default function AdminDashboard({ onNavigate=()=>{} }) {
  const state=useAdminDashboard();
  if(state.isLoading)return <DashboardSkeleton/>;
  if(state.error&&!state.data)return <ErrorState message={state.error} onRetry={state.refresh}/>;
  const data=state.data||{};const sales=data.sales||{};const growth=data.comparison?.salesGrowthPercent;
  const salesLabel=state.filters.preset==='today'?'Today Sales':state.filters.preset==='month'?'This Month Sales':'Period Net Sales';
  const navigate=(section,filters={})=>onNavigate(section,filters);
  return <section className="space-y-5 pb-8">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{data.businessName} · {data.branchName}</p><h1 className="mt-1 text-3xl font-black text-slate-950">Admin Dashboard</h1><p className="mt-1 flex flex-wrap items-center gap-2 text-sm text-slate-500"><span className="flex items-center gap-1"><CalendarDays size={14}/>{formatDate(new Date())}</span><span>·</span><span>Last updated {state.lastUpdated?formatTime(state.lastUpdated):'—'}</span><span>· Malaysia time</span></p></div><button disabled={state.isRefreshing} onClick={state.refresh} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold shadow-sm disabled:opacity-60"><RefreshCw size={16} className={state.isRefreshing?'animate-spin':''}/>{state.isRefreshing?'Refreshing':'Refresh'}</button></header>
    <DashboardFilters state={state} data={data}/>
    {state.error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{state.error} Showing the last successful snapshot from {state.lastUpdated?formatDateTime(state.lastUpdated):'an earlier refresh'}.</div>}
    {data.access?.reports?<><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><MetricCard label={salesLabel} value={formatCurrency(sales.netSales)} growth={growth} Icon={TrendingUp}/><MetricCard label="Gross Sales" value={formatCurrency(sales.grossSales)} helper={`${formatCurrency(sales.discounts)} discounts · ${formatCurrency(sales.refunds)} refunds`} Icon={BarChart3} tone="blue"/><MetricCard label="Total Orders" value={formatNumber(data.orders?.total)} helper="Created in selected period" Icon={ShoppingBag} tone="violet" onClick={()=>navigate('orders',{})}/><MetricCard label="Average Order Value" value={formatCurrency(sales.averageOrderValue)} helper={`${formatNumber(sales.settledOrders)} settled orders`} Icon={ReceiptText} tone="green"/><MetricCard label="Open Orders" value={formatNumber(data.orders?.open)} helper="Current state of orders created in period" Icon={Utensils} tone="red" onClick={()=>navigate('orders',{})}/></div><p className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500">Net sales: {formatCurrency(sales.grossSales)} gross − {formatCurrency(sales.discounts)} discounts − {formatCurrency(sales.refunds)} refunds + {formatCurrency(sales.tax)} tax + {formatCurrency(sales.serviceCharge)} service charge = <strong className="text-slate-900">{formatCurrency(sales.netSales)}</strong></p></>:<div className="rounded-xl border bg-white p-4 text-sm text-slate-500">Sales KPIs require <code>report.view</code>.</div>}
    <div className="grid gap-5 xl:grid-cols-3">{data.access?.reports&&<SalesPerformance data={data} state={state}/>} {data.access?.payments&&<PaymentOverview data={data} navigate={navigate}/>}</div>
    <div className="grid gap-5 xl:grid-cols-2">{data.access?.orders&&<OrderOverview data={data} navigate={navigate}/>}<LiveOperations data={data} navigate={navigate}/></div>
    <div className="grid gap-5 xl:grid-cols-2">{data.access?.reports&&<TopProducts data={data} navigate={navigate}/>}<AlertsPanel data={data} navigate={navigate}/></div>
    {data.access?.orders&&<RecentOrders data={data} navigate={navigate}/>}
    <div className="grid gap-5 xl:grid-cols-2">{data.access?.staffPerformance&&<StaffPerformance data={data}/>} {data.access?.audit&&<RecentActivity data={data} navigate={navigate}/>}</div>
  </section>;
}
