import { useCallback, useEffect, useState } from 'react';
import { getBranchManagement, saveBranchConfiguration } from '../../services/organization.service';
import TerminalManagement from './TerminalManagement';
import StaffAssignmentPanel from './StaffAssignmentPanel';
const panels = [['overview','Overview'],['terminals','Terminals'],['staff','Staff'],['tables','Tables'],['pos','POS & payment'],['tax','Tax & receipt'],['kitchen','Kitchen / KDS'],['audit','Audit']];
function Switch({ label, value, onChange }) { return <label className="flex items-center justify-between gap-4 rounded-xl border p-3 text-sm"><span>{label}</span><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)} /></label>; }
export default function BranchManagement({ branchId, permissions, onBack }) {
 const [data,setData] = useState(null),[panel,setPanel] = useState('overview'),[draft,setDraft] = useState({}),[error,setError] = useState(''),[message,setMessage] = useState(''),[loading,setLoading] = useState(true),[saving,setSaving] = useState(false);
 const load = useCallback(async()=>{ setLoading(true); setError(''); try { const r=await getBranchManagement(branchId); if(r.error) throw r.error; setData(r.data); setDraft({}); } catch(e) { setError(e.message); } finally { setLoading(false); } },[branchId]);
 useEffect(()=>{void load();},[load]);
 const save=async()=>{if(saving)return; setSaving(true);setError('');setMessage(''); try {const r=await saveBranchConfiguration(branchId,draft,data.branch.revision);if(r.error)throw r.error;setData(r.data);setDraft({});setMessage('Branch settings saved. New orders use the updated configuration.');window.dispatchEvent(new CustomEvent('pos-settings-updated'));}catch(e){setError(e.message);}finally{setSaving(false);}};
 const effective={...data?.settings,...draft};
 const group=(key)=>({...data?.settings?.[key],...draft[key]});
 const update=(key,value)=>setDraft(d=>({...d,[key]:value}));
 const updateGroup=(key,field,value)=>update(key,{...group(key),[field]:value});
 const canManage=permissions.includes('settings.manage');
 return <section className="space-y-5"><button onClick={onBack} className="text-sm font-bold text-slate-600">← Branches</button>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-700">{error}<button className="ml-4 underline" onClick={load}>Reload</button></div>}{message&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{message}</p>}
 {loading?<p role="status">Loading branch…</p>:data&&<><header className="rounded-3xl bg-[#171717] p-7 text-white"><p className="text-xs uppercase tracking-widest text-[#D4AF37]">{data.company.name} · {data.branch.status}</p><h1 className="mt-2 text-2xl font-black">{data.branch.code} — {data.branch.name}</h1><p className="mt-2 text-sm text-slate-300">{data.settings.currency_code} · {data.settings.timezone}</p></header>
 <nav aria-label="Branch sections" className="flex flex-wrap gap-2">{panels.map(([id,label])=><button key={id} aria-current={panel===id?'page':undefined} onClick={()=>setPanel(id)} className={`rounded-xl px-4 py-2 text-sm font-bold ${panel===id?'bg-[#D4AF37]':'border bg-white'}`}>{label}</button>)}</nav>
 {panel==='overview'&&<><div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{[['Active terminals',data.activeTerminalCount],['Active staff',data.activeStaffCount],["Today’s orders",data.todayOrders],['Open orders',data.openOrders]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><dl className="grid gap-5 rounded-2xl border bg-white p-6 sm:grid-cols-2">{[['Company',data.company.name],['Address',data.branch.address],['Phone',data.branch.phone],['Email',data.branch.email],['Registration no.',data.branch.registration_no],['Updated',new Date(data.branch.updated_at).toLocaleString()]].map(([k,v])=><div key={k}><dt className="text-xs uppercase text-slate-500">{k}</dt><dd className="mt-1 font-medium">{v||'Not configured'}</dd></div>)}</dl><p className="text-xs text-slate-500">Counts are loaded from the database. Today uses the branch timezone. Reload to refresh.</p><button onClick={load} className="rounded-xl border bg-white px-4 py-2">Refresh overview</button></>}
 {panel==='terminals'&&<TerminalManagement branchId={branchId} permissions={permissions}/>}
 {panel==='staff'&&<StaffAssignmentPanel data={data} branchId={branchId} permissions={permissions} onReload={load} onError={setError} />}
 {panel==='tables'&&<div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Dining areas & tables</h2><div className="grid gap-3 md:grid-cols-3">{data.tables.map(t=><div className="rounded-xl border p-4" key={t.id}><strong>{t.table_number} {t.table_name}</strong><p className="text-sm text-slate-500">{t.area||'No area'} · {t.capacity} seats</p><p className="mt-2 text-xs">{t.is_active?t.status:'INACTIVE'}</p></div>)}</div>{!data.tables.length&&<p>No tables configured for this branch.</p>}<a href={`#admin/tables?branchId=${branchId}`} className="mt-5 inline-block font-bold underline">Manage tables</a></div>}
 {panel==='pos'&&<fieldset disabled={!canManage||saving} className="space-y-5 rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold">POS settings</h2><div className="grid gap-3 md:grid-cols-2">{[['dineInEnabled','Dine-in'],['takeawayEnabled','Takeaway'],['splitPaymentEnabled','Split payments'],['partialPaymentEnabled','Partial payments'],['voucherEnabled','Vouchers'],['promotionEnabled','Promotions'],['autoLockEnabled','Auto lock']].map(([key,label])=><Switch key={key} label={label} value={group('pos')[key]??true} onChange={v=>updateGroup('pos',key,v)}/>)}</div><label className="block text-sm">Idle timeout (minutes)<input type="number" min="1" max="120" value={group('pos').idleTimeoutMinutes??3} onChange={e=>updateGroup('pos','idleTimeoutMinutes',Number(e.target.value))} className="ml-3 rounded-lg border p-2"/></label><p className="text-xs text-slate-500">Staff PIN is required to start a session. Normal work uses that session.</p><h2 className="text-lg font-bold">Payment settings</h2><div className="grid gap-3 md:grid-cols-2">{[['cashEnabled','Cash'],['cardEnabled','Card'],['qrEnabled','Physical QR'],['splitPaymentEnabled','Split payments'],['partialPaymentAllowed','Partial payments'],['referenceRequired','Require non-cash reference']].map(([key,label])=><Switch key={key} label={label} value={group('payment')[key]??key!=='referenceRequired'} onChange={v=>updateGroup('payment',key,v)}/>)}</div><p className="text-xs text-slate-500">QR providers use the existing physical payment methods. Provider availability is also validated by the backend.</p></fieldset>}
 {panel==='tax'&&<fieldset disabled={!canManage||saving} className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold">Tax & service charge</h2><Switch label="Tax enabled" value={effective.tax_enabled} onChange={v=>update('tax_enabled',v)}/><div className="grid gap-4 md:grid-cols-2">{[['tax_name','Tax name'],['tax_rate','Tax rate (%)'],['service_charge_name','Service charge name'],['service_charge_rate','Service charge rate (%)']].map(([key,label])=><label key={key} className="text-sm">{label}<input type={key.endsWith('rate')?'number':'text'} min="0" max="100" step="0.01" value={effective[key]??''} onChange={e=>update(key,key.endsWith('rate')?Number(e.target.value):e.target.value)} className="mt-1 block w-full rounded-xl border p-3"/></label>)}</div><Switch label="Service charge enabled" value={effective.service_charge_enabled} onChange={v=>update('service_charge_enabled',v)}/><label className="block text-sm">Tax calculation<select value={effective.tax_mode} onChange={e=>update('tax_mode',e.target.value)} className="ml-3 rounded-xl border p-3"><option value="EXCLUSIVE">Tax exclusive</option><option value="INCLUSIVE">Price includes tax</option></select></label><h2 className="pt-3 text-lg font-bold">Receipt</h2><p className="text-sm text-slate-500">Company and branch details populate the receipt; totals come from the final order and payments.</p><label className="block text-sm">Receipt footer<textarea className="mt-1 block w-full rounded-xl border p-3" value={group('receipt_config').receiptFooter||''} onChange={e=>updateGroup('receipt_config','receiptFooter',e.target.value)}/></label><div className="grid gap-3 md:grid-cols-2">{[['showOrderNumber','Order number'],['showStaffName','Cashier'],['showPaymentMethod','Payment method'],['showTax','Tax'],['showServiceCharge','Service charge'],['showDiscount','Discount']].map(([key,label])=><Switch key={key} label={label} value={group('receipt_config')[key]??true} onChange={v=>updateGroup('receipt_config',key,v)}/>)}</div></fieldset>}
 {panel==='kitchen'&&<div className="rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold">Kitchen / KDS</h2><p className="mt-2 text-sm text-slate-500">KDS uses this branch’s registered terminals and staff sessions. Existing kitchen ticket statuses and batches are preserved.</p>{data.terminals.filter(t=>t.terminal_type==='KDS').map(t=><p className="mt-4 rounded-xl border p-4" key={t.id}>{t.terminal_code} · {t.name} · {t.status}<span className="block text-xs text-slate-500">Last contact: {t.last_seen_at?new Date(t.last_seen_at).toLocaleString():'Never'}</span></p>)}{!data.terminals.some(t=>t.terminal_type==='KDS')&&<p className="mt-4">No KDS terminal registered.</p>}<button className="mt-4 rounded-xl border px-4 py-2" onClick={()=>setPanel('terminals')}>Manage KDS terminals</button></div>}
 {panel==='audit'&&<div className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Recent branch audit events</h2>{data.audit.map(a=><article className="border-b py-3" key={a.id}><strong className="text-sm">{a.action}</strong><p className="text-xs text-slate-500">{new Date(a.created_at).toLocaleString()} · {a.entity_type} · {a.actor_id}</p></article>)}{!data.audit.length&&<p className="text-sm text-slate-500">No visible audit events.</p>}</div>}
 {Object.keys(draft).length>0&&canManage&&<div className="sticky bottom-0 flex items-center gap-3 rounded-xl border bg-white p-4 shadow-lg"><button disabled={saving} onClick={save} className="rounded-xl bg-[#D4AF37] px-5 py-3 font-bold">{saving?'Saving…':'Save branch settings'}</button><button disabled={saving} onClick={()=>setDraft({})} className="rounded-xl border px-5 py-3">Discard changes</button><span className="text-xs text-slate-500">Unsaved changes</span></div>}
 </>}
 </section>;
}
