import React,{useMemo,useState} from 'react';
import { Pencil,Plus,Search,X } from 'lucide-react';
import { useCategoryManagement } from '../../hooks/useCategoryManagement';

const blank={name:'',description:'',status:true,displayOrder:0};
export default function CategoryManagement(){const state=useCategoryManagement();const [query,setQuery]=useState('');const [editing,setEditing]=useState(null);const [form,setForm]=useState(blank);
 const rows=useMemo(()=>state.categories.filter(c=>`${c.code} ${c.name}`.toLowerCase().includes(query.toLowerCase())),[state.categories,query]);
 const open=(c=null)=>{setEditing(c||{isNew:true});setForm(c?{name:c.name,description:c.description,status:c.isActive,displayOrder:c.displayOrder||0}:blank);};
 const submit=async e=>{e.preventDefault();if(await state.save(editing.id||null,{...form,displayOrder:Number(form.displayOrder)}))setEditing(null);};
 return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-black">Categories</h1><p className="text-sm text-gray-500">Inactive categories are hidden from the POS menu.</p></div><button onClick={()=>open()} className="flex items-center gap-2 rounded-xl bg-[#D4AF37] px-4 py-3 font-black"><Plus size={17}/>Add Category</button></div>
 <div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search categories" className="w-full rounded-xl border bg-white py-2.5 pl-10 pr-3"/></div>
 {state.error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}{state.notice&&<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{state.notice}</p>}
 {state.isLoading?<p>Loading categories…</p>:<div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full text-sm"><thead className="bg-gray-100 text-left text-xs uppercase text-gray-500"><tr><th className="p-3">Order</th><th className="p-3">Code</th><th className="p-3">Category</th><th className="p-3">Products</th><th className="p-3">Status</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id} className="border-t"><td className="p-3">{c.displayOrder}</td><td className="p-3 font-mono">{c.code}</td><td className="p-3"><strong>{c.name}</strong><p className="text-xs text-gray-400">{c.description}</p></td><td className="p-3">{c.productCount}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${c.isActive?'bg-emerald-100 text-emerald-700':'bg-gray-200'}`}>{c.isActive?'ACTIVE':'INACTIVE'}</span></td><td className="p-3 text-right"><button onClick={()=>open(c)} className="rounded-lg border p-2"><Pencil size={15}/></button></td></tr>)}</tbody></table></div>}
 {editing&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{editing.id?'Edit':'Add'} Category</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><label className="block text-sm font-bold">Name<input required maxLength={150} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="mt-4 block text-sm font-bold">Description<textarea maxLength={1000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="mt-4 block text-sm font-bold">Display order<input type="number" min="0" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:e.target.value})} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="mt-4 flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.status} onChange={e=>setForm({...form,status:e.target.checked})}/>Active</label><button disabled={state.isSaving} className="mt-6 w-full rounded-xl bg-[#D4AF37] p-3 font-black">{state.isSaving?'Saving…':'Save Category'}</button></form></div>}
 </section>}
