import React, { useEffect, useState } from 'react';
import { listDiscountActivity } from '../../services/organization.service';
const money = (value) => `RM ${Number(value || 0).toFixed(2)}`;
export default function DiscountActivity({ initialKind = '' }) {
  const [rows, setRows] = useState([]); const [error, setError] = useState('');
  useEffect(() => { let active = true; void listDiscountActivity().then(({data,error: queryError})=>{ if (!active) return; if(queryError) setError(queryError.message); else setRows(data||[]); }); return () => { active=false; }; }, []);
  const visibleRows = initialKind ? rows.filter(row => row.kind === initialKind) : rows;
  const totals = (kind) => rows.filter(row=>row.kind===kind && row.status!=='INVALID').reduce((sum,row)=>sum+Number(row.amount||0),0);
  return <section className="space-y-5"><div><h2 className="text-xl font-black">Discount Activity</h2><p className="text-sm text-slate-500">Promotion usage, voucher redemptions, manual discounts, and manager overrides.</p></div>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-4">{[['Promotion Usage','PROMOTION'],['Voucher Redemption','VOUCHER'],['Manual Discounts','MANUAL'],['Manager Overrides','OVERRIDE']].map(([label,kind])=><div key={kind} className="rounded-xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{money(totals(kind))}</strong><span className="text-xs text-slate-500">{rows.filter(row=>row.kind===kind).length} records</span></div>)}</div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Time</th><th className="p-3">Type</th><th className="p-3">Discount</th><th className="p-3">Order</th><th className="p-3">Amount</th><th className="p-3">Status</th></tr></thead><tbody>{visibleRows.map(row=><tr className="border-t" key={row.id}><td className="p-3 text-xs">{new Date(row.created_at).toLocaleString()}</td><td className="p-3">{row.kind}</td><td className="p-3 font-semibold">{row.label}</td><td className="p-3">{row.order?.order_number||'—'}</td><td className="p-3">-{money(row.amount)}</td><td className="p-3">{row.status}</td></tr>)}{!visibleRows.length&&!error&&<tr><td colSpan="6" className="p-10 text-center text-slate-500">No discount activity yet.</td></tr>}</tbody></table></div></section>;
}
