import React, { useEffect, useMemo, useState } from 'react';
import { listEinvoiceDocuments, listEinvoiceProfiles, setEinvoiceProfileStatus } from '../../features/einvoice/einvoiceRepository';
import StatusBadge from '../ui/StatusBadge';
import PageHeader from '../ui/PageHeader';
import Button from '../ui/Button';
import SearchFilterBar, { FilterSelect } from '../ui/SearchFilterBar';
export default function EinvoiceOverview() {
  const [profiles, setProfiles] = useState([]); const [documents, setDocuments] = useState([]); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [environmentFilter, setEnvironmentFilter] = useState('');
  const refresh = async () => { const [p, d] = await Promise.all([listEinvoiceProfiles(), listEinvoiceDocuments()]); if (p.error || d.error) setError((p.error || d.error).message); else { setProfiles(p.data || []); setDocuments(d.data || []); } };
  useEffect(() => { void refresh(); }, []);
  const filteredProfiles = useMemo(() => profiles.filter((profile) => (!statusFilter || profile.status === statusFilter) && (!environmentFilter || profile.environment === environmentFilter) && `${profile.legal_name} ${profile.trading_name || ''} ${profile.tin || ''} ${profile.registration_number || ''}`.toLowerCase().includes(query.trim().toLowerCase())), [profiles, query, statusFilter, environmentFilter]);
  return <section className="space-y-5"><PageHeader eyebrow="Compliance" title="e-Invoice" description="Optional Malaysia e-Invoice integration and document status." />{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border bg-white p-4 shadow-sm"><span className="text-xs text-slate-500">Configured companies</span><strong className="mt-1 block text-2xl">{profiles.length}</strong></div><div className="rounded-xl border bg-white p-4 shadow-sm"><span className="text-xs text-slate-500">Valid documents</span><strong className="mt-1 block text-2xl">{documents.filter((d) => d.internal_status === 'VALID').length}</strong></div><div className="rounded-xl border bg-white p-4 shadow-sm"><span className="text-xs text-slate-500">Needs attention</span><strong className="mt-1 block text-2xl">{documents.filter((d) => ['FAILED','INVALID'].includes(d.internal_status)).length}</strong></div></div><SearchFilterBar query={query} onQueryChange={setQuery} placeholder="Search company, TIN or registration number" resultCount={filteredProfiles.length} onReset={() => { setQuery(''); setStatusFilter(''); setEnvironmentFilter(''); }}><FilterSelect label="Status" value={statusFilter} onChange={setStatusFilter} options={[{value:'',label:'All'},{value:'ACTIVE',label:'Active'},{value:'CONNECTED',label:'Connected'},{value:'CONFIGURING',label:'Configuring'},{value:'DISABLED',label:'Disabled'},{value:'CONNECTION_ERROR',label:'Error'}]} /><FilterSelect label="Environment" value={environmentFilter} onChange={setEnvironmentFilter} options={[{value:'',label:'All'},{value:'SANDBOX',label:'Sandbox'},{value:'PRODUCTION',label:'Production'}]} /></SearchFilterBar><div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Company</th><th className="p-3">Environment</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{filteredProfiles.map((p) => <tr className="border-t" key={p.id}><td className="p-3 font-semibold">{p.legal_name}</td><td className="p-3">{p.environment}</td><td className="p-3"><StatusBadge value={p.status} /></td><td className="p-3">{['ACTIVE','DISABLED'].includes(p.status) && <Button size="sm" variant={p.status === 'ACTIVE' ? 'secondary' : 'primary'} onClick={async () => { await setEinvoiceProfileStatus(p.id, p.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'); await refresh(); }}>{p.status === 'ACTIVE' ? 'Disable' : 'Enable'}</Button>}</td></tr>)}{filteredProfiles.length === 0 && <tr><td colSpan="4" className="p-10 text-center text-sm text-slate-500">No companies match the selected filters.</td></tr>}</tbody></table></div></section>;
}
