import { useEffect, useState } from 'react';
import { fetchManualQrSettings, updateManualQrSettings, uploadManualQrImage } from '../../repositories/qr-payment.repository';
export default function QrPaymentSettings() {
  const [form,setForm]=useState({enabled:false,imageUrl:'',displayName:'Restaurant DuitNow QR',merchantName:'Restaurant',settlementBank:'',referenceRequired:false}); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetchManualQrSettings().then(({data,error})=>{if(error)setMessage(error.message);else if(data)setForm(data);});},[]);
  const save=async()=>{setSaving(true);setMessage('');const {data,error}=await updateManualQrSettings(form);setSaving(false);setMessage(error?error.message:'DuitNow QR settings saved and audited.');if(data)setForm(data);};
  const upload=async(event)=>{const file=event.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5242880){setMessage('Choose a PNG, JPG, or WebP image up to 5 MB.');return;}setSaving(true);const path=`qr/${crypto.randomUUID()}.${file.type.split('/')[1].replace('jpeg','jpg')}`;const {data,error}=await uploadManualQrImage(path,file);if(error){setMessage(error.message);setSaving(false);return;}setForm({...form,imageUrl:data});setMessage('QR uploaded. Click Save QR settings to apply it.');setSaving(false);};
  return <section className="max-w-2xl space-y-5"><header><h1 className="text-3xl font-black">DuitNow QR Payment</h1><p className="text-sm text-slate-500">Configure the static QR shown to customers. Cashier confirmation is always required.</p></header><div className="space-y-4 rounded-2xl border bg-white p-5"><label className="flex items-center gap-3 font-bold"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enable DuitNow QR</label>{[['displayName','Display name'],['merchantName','Merchant name'],['settlementBank','Settlement bank']].map(([key,label])=><label key={key} className="block text-sm font-bold">{label}<input className="mt-1 w-full rounded-xl border p-3 font-normal" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={form.referenceRequired} onChange={e=>setForm({...form,referenceRequired:e.target.checked})}/> Require payment reference</label><label className="block text-sm font-bold">Upload QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} className="mt-1 w-full rounded-xl border p-3 font-normal"/></label><label className="block text-sm font-bold">QR image URL<input className="mt-1 w-full rounded-xl border p-3 font-normal" placeholder="https://..." value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label>{form.imageUrl&&<img src={form.imageUrl} alt="DuitNow QR preview" className="h-48 w-48 rounded-xl border object-contain p-2"/>}<button disabled={saving} onClick={save} className="rounded-xl bg-amber-400 px-5 py-3 font-black disabled:opacity-60">{saving?'Saving…':'Save QR settings'}</button>{message&&<p className="text-sm text-slate-600">{message}</p>}</div></section>;
}
