import { useCallback, useEffect, useState } from 'react';
import { bindTerminalAccount, changeTerminalStatus, listBranches, listTerminals, reassignTerminal, saveTerminal } from '../../services/organization.service';
import { getDeviceIdentifier } from '../../services/terminal-context.service';

const blank = { code: '', name: '', branchId: '', type: 'CASHIER' };
const types = ['CASHIER', 'WAITER', 'SELF_ORDER', 'KITCHEN', 'ADMIN', 'POS', 'KDS'];

export default function TerminalManagement({ branchId = '', permissions = [] }) {
  const [rows, setRows] = useState([]); const [branches, setBranches] = useState([]); const [form, setForm] = useState({ ...blank, branchId });
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('ALL'); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [bindingTerminal, setBindingTerminal] = useState(null); const [terminalEmail, setTerminalEmail] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [terminals, branchRows] = await Promise.all([listTerminals(branchId), listBranches()]); if (terminals.error || branchRows.error) throw (terminals.error || branchRows.error); setRows(terminals.data || []); setBranches(branchRows.data || []); setForm((current) => ({ ...current, branchId: branchId || current.branchId || branchRows.data?.[0]?.id || '' })); } catch (cause) { setError(cause.message); } finally { setLoading(false); } }, [branchId]);
  useEffect(() => { void load(); }, [load]);
  const run = async (operation, success) => { if (busy) return; setBusy(true); setError(''); try { const result = await operation(); if (result.error) throw result.error; setMessage(success); await load(); } catch (cause) { setError(cause.message || 'Unable to complete action.'); } finally { setBusy(false); } };
  const state = (terminal) => terminal.status !== 'ACTIVE' ? (terminal.lock_status === 'LOCKED' ? 'LOCKED' : 'DISABLED') : !terminal.last_seen_at ? 'UNKNOWN' : Date.now() - new Date(terminal.last_seen_at).getTime() < 120000 ? 'ONLINE' : 'OFFLINE';
  const visible = rows.filter((terminal) => (!search || `${terminal.terminal_code} ${terminal.name}`.toLowerCase().includes(search.toLowerCase())) && (filter === 'ALL' || state(terminal) === filter));
  const canBindAccount = permissions.includes('terminal.update') && permissions.includes('user.edit');
  const submitBinding = async (event) => { event.preventDefault(); if (!bindingTerminal) return; await run(() => bindTerminalAccount(bindingTerminal.id, terminalEmail), `Terminal account bound to ${bindingTerminal.terminal_code}.`); setBindingTerminal(null); setTerminalEmail(''); };
  return <section className="space-y-5">
    <header><h2 className="text-xl font-bold">Terminals</h2><p className="text-sm text-slate-500">Online status uses the last two minutes of heartbeat. Registration, account binding, and reassignment are administrator-controlled.</p></header>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{message}</p>}
    <div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><input aria-label="Search terminals" placeholder="Search terminals…" value={search} onChange={(event) => setSearch(event.target.value)} className="min-w-64 rounded-xl border p-3"/><select aria-label="Filter terminal status" value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-xl border p-3"><option>ALL</option><option>ONLINE</option><option>OFFLINE</option><option>UNKNOWN</option><option>LOCKED</option><option>DISABLED</option></select></div>
    {(permissions.includes('terminal.create') || form.id && permissions.includes('terminal.update')) && <form onSubmit={async (event) => { event.preventDefault(); await run(() => saveTerminal(form), 'Terminal saved.'); }} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><label>Terminal code<input required disabled={Boolean(form.id) || busy} className="mt-1 block w-full rounded-xl border p-3" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })}/></label><label>Name<input required disabled={busy} className="mt-1 block w-full rounded-xl border p-3" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>Branch<select disabled={Boolean(branchId) || Boolean(form.id) || busy} className="mt-1 block w-full rounded-xl border p-3" value={form.branchId} onChange={(event) => setForm({ ...form, branchId: event.target.value })}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.code} · {branch.name}</option>)}</select></label><label>Type<select disabled={busy} className="mt-1 block w-full rounded-xl border p-3" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><button disabled={busy} className="rounded-xl bg-[#D4AF37] p-3 font-bold">{form.id ? 'Save terminal' : 'Create terminal'}</button></form>}
    {loading ? <p role="status">Loading terminals…</p> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Terminal', 'Branch', 'Type', 'Status', 'Last seen', 'Actions'].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{visible.map((terminal) => <tr key={terminal.id} className="border-t"><td className="p-3"><strong>{terminal.terminal_code}</strong><span className="block text-slate-500">{terminal.name}</span></td><td className="p-3">{branches.find((branch) => branch.id === terminal.branch_id)?.code || '—'}</td><td className="p-3">{terminal.terminal_type}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{state(terminal)}</span></td><td className="p-3">{terminal.last_seen_at ? new Date(terminal.last_seen_at).toLocaleString() : 'Never'}</td><td className="p-3"><div className="flex flex-wrap gap-3">{permissions.includes('terminal.update') && <><button type="button" onClick={() => setForm({ id: terminal.id, code: terminal.terminal_code, name: terminal.name, branchId: terminal.branch_id, type: terminal.terminal_type })}>Edit</button>{terminal.registration_status !== 'REGISTERED' && <button type="button" onClick={() => void run(() => changeTerminalStatus(terminal.id, 'REGISTER', getDeviceIdentifier()), 'Browser registered.')}>Register</button>}{terminal.registration_status === 'REGISTERED' && terminal.status !== 'ACTIVE' && <button type="button" onClick={() => void run(() => changeTerminalStatus(terminal.id, 'ACTIVATE'), 'Terminal enabled.')}>Enable</button>}<button type="button" onClick={() => void run(() => changeTerminalStatus(terminal.id, terminal.lock_status === 'LOCKED' ? 'UNLOCK' : 'LOCK'), terminal.lock_status === 'LOCKED' ? 'Terminal unlocked.' : 'Terminal locked.')}>{terminal.lock_status === 'LOCKED' ? 'Unlock' : 'Lock'}</button>{branches.length > 1 && <select aria-label={`Reassign ${terminal.terminal_code}`} value="" onChange={(event) => event.target.value && void run(() => reassignTerminal(terminal.id, event.target.value), 'Terminal reassigned.')}><option value="">Reassign…</option>{branches.filter((branch) => branch.id !== terminal.branch_id).map((branch) => <option key={branch.id} value={branch.id}>{branch.code}</option>)}</select>}</>}{canBindAccount && <button type="button" className="font-bold text-blue-700 underline" onClick={() => { setBindingTerminal(terminal); setTerminalEmail(''); }}>Bind account</button>}{permissions.includes('terminal.deactivate') && terminal.status === 'ACTIVE' && <button type="button" className="text-red-700" onClick={() => void run(() => changeTerminalStatus(terminal.id, 'DEACTIVATE'), 'Terminal disabled.')}>Disable</button>}</div></td></tr>)}{!visible.length && <tr><td colSpan="6" className="p-8 text-center text-slate-500">No terminals match the filters.</td></tr>}</tbody></table></div>}
    {bindingTerminal && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4"><form onSubmit={submitBinding} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-black">Bind terminal account</h3><p className="mt-2 text-sm text-slate-600">Bind an existing dedicated terminal email account to <strong>{bindingTerminal.terminal_code}</strong>. Administrator accounts cannot be bound.</p><label className="mt-5 block text-sm font-bold">Terminal account email<input required type="email" autoComplete="email" value={terminalEmail} onChange={(event) => setTerminalEmail(event.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><p className="mt-3 text-xs text-slate-500">The terminal must be registered, active, and unlocked. This change is audited.</p><div className="mt-6 flex gap-3"><button type="button" disabled={busy} onClick={() => setBindingTerminal(null)} className="flex-1 rounded-xl border p-3 font-bold">Cancel</button><button disabled={busy} className="flex-1 rounded-xl bg-blue-600 p-3 font-black text-white">{busy ? 'Binding…' : 'Bind account'}</button></div></form></div>}
  </section>;
}
