import { useCallback, useEffect, useState } from 'react';
import { listBranches, listTerminals, saveTerminal, changeTerminalStatus } from '../../services/organization.service';
import { getDeviceIdentifier } from '../../services/terminal-context.service';
const blank = { code: '', name: '', branchId: '', type: 'POS' };
export default function TerminalManagement({ branchId = '', permissions = [] }) {
 const [rows,setRows] = useState([]), [branches,setBranches] = useState([]), [form,setForm] = useState({ ...blank, branchId }), [error,setError] = useState(''), [message,setMessage] = useState(''), [busy,setBusy] = useState(false), [loading,setLoading] = useState(true);
 const load = useCallback(async () => { setLoading(true); try { const [t,b] = await Promise.all([listTerminals(branchId),listBranches()]); if(t.error || b.error) throw t.error || b.error; setRows(t.data || []); setBranches(b.data || []); setForm(f => ({...f,branchId:branchId || f.branchId || b.data?.[0]?.id || ''})); } catch(e) { setError(e.message); } finally { setLoading(false); } }, [branchId]);
 useEffect(() => { void load(); }, [load]);
 const run = async (operation,success) => { if(busy) return; setBusy(true); setError(''); setMessage(''); try { const r = await operation(); if(r.error) throw r.error; setMessage(success); await load(); return true; } catch(e) { setError(e.message); return false; } finally { setBusy(false); } };
 return <section className="space-y-5"><h2 className="text-xl font-bold">Terminals</h2><p className="text-sm text-slate-500">Register this browser once, then activate its terminal. Last seen records server contact; it does not prove a device is currently online.</p>
 {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{message}</p>}
 {(permissions.includes('terminal.create') || form.id && permissions.includes('terminal.update')) && <form onSubmit={async e => { e.preventDefault(); if(await run(() => saveTerminal(form),'Terminal saved.')) setForm({...blank,branchId:form.branchId}); }} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><label>Terminal code<input required disabled={!!form.id || busy} className="mt-1 block w-full rounded-xl border p-3" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>Name<input required disabled={busy} className="mt-1 block w-full rounded-xl border p-3" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Branch<select disabled={!!branchId || !!form.id || busy} className="mt-1 block w-full rounded-xl border p-3" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></label><label>Type<select disabled={busy} className="mt-1 block w-full rounded-xl border p-3" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>POS</option><option>KDS</option></select></label><button disabled={busy} className="rounded-xl bg-[#D4AF37] p-3 font-bold disabled:opacity-50">{form.id?'Save terminal':'Create terminal'}</button>{form.id && <button type="button" onClick={()=>setForm({...blank,branchId})}>Cancel edit</button>}</form>}
 {loading ? <p role="status">Loading terminals…</p> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Terminal','Branch','Type','Registration','Status','Last seen','Actions'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-t"><td className="p-3"><strong>{t.terminal_code}</strong><span className="block text-slate-500">{t.name}</span></td><td className="p-3">{branches.find(b=>b.id===t.branch_id)?.code}</td><td className="p-3">{t.terminal_type}</td><td className="p-3">{t.registration_status}</td><td className="p-3">{t.status}</td><td className="p-3">{t.last_seen_at?new Date(t.last_seen_at).toLocaleString():'Never'}</td><td className="p-3"><div className="flex flex-wrap gap-3">{permissions.includes('terminal.update') && <><button disabled={busy} onClick={()=>setForm({id:t.id,code:t.terminal_code,name:t.name,branchId:t.branch_id,type:t.terminal_type})}>Edit</button>{t.registration_status!=='REGISTERED' && <button disabled={busy} onClick={()=>void run(()=>changeTerminalStatus(t.id,'REGISTER',getDeviceIdentifier()),'This browser registered. Activate the terminal to use POS.')}>Register this browser</button>}{t.registration_status==='REGISTERED' && t.status!=='ACTIVE' && <button disabled={busy} onClick={()=>void run(()=>changeTerminalStatus(t.id,'ACTIVATE'),'Terminal activated.')}>Activate</button>}</>}{permissions.includes('terminal.deactivate') && t.status==='ACTIVE' && <button disabled={busy} className="text-red-700" onClick={()=>void run(()=>changeTerminalStatus(t.id,'DEACTIVATE'),'Terminal deactivated.')}>Deactivate</button>}</div></td></tr>)}{!rows.length && <tr><td colSpan={7} className="p-8 text-center">No terminals configured.</td></tr>}</tbody></table></div>}
 </section>;
}
