import { useEffect, useState } from 'react';
import { Check, Copy, Plus, Search, X } from 'lucide-react';
import { useAdminUsers } from '../../hooks/useAdminUsers';
import { listBranches } from '../../services/organization.service';

const roles = ['MANAGER', 'CASHIER', 'WAITER', 'KITCHEN'];
const empty = { name: '', staffCode: '', branchId: '', role: 'CASHIER' };

export default function UserManagement() {
  const state = useAdminUsers();
  const [form, setForm] = useState(empty), [creating, setCreating] = useState(false), [branches, setBranches] = useState([]), [temporaryPin, setTemporaryPin] = useState(''), [copied, setCopied] = useState(false);
  useEffect(() => { void listBranches().then(result => setBranches(result.data || [])); }, []);
  const submit = async (event) => {
    event.preventDefault();
    const result = await state.invite(form);
    if (result) { setCreating(false); setForm(empty); setTemporaryPin(result.temporaryPin || result.data?.temporaryPin || ''); }
  };
  const copy = async () => { if (temporaryPin) { await navigator.clipboard.writeText(temporaryPin); setCopied(true); } };
  return <section className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Staff</h1><p className="text-sm text-gray-500">Staff have no email or password. They sign in on a terminal using their staff PIN.</p></div><button onClick={() => setCreating(true)} className="flex items-center gap-2 rounded-xl bg-[#D4AF37] px-4 py-3 font-black"><Plus size={17}/>Create Staff</button></header>
    <div className="flex flex-wrap gap-3"><label className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input aria-label="Search staff" value={state.search} onChange={event => state.setSearch(event.target.value)} placeholder="Search name, staff code, role…" className="w-full rounded-xl border bg-white py-2.5 pl-10"/></label></div>
    {state.error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{state.error}</p>}{state.notice && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-700">{state.notice}</p>}
    {state.isLoading ? <p role="status">Loading staff…</p> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{['Staff','Role','Branch','POS PIN','Terminal access'].map(label => <th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{state.users.map(user => <tr key={user.id} className="border-t"><td className="p-4"><strong>{user.name}</strong><span className="block text-xs text-slate-500">{user.staff_code || user.username}</span></td><td className="p-4 font-bold">{user.role_name}</td><td className="p-4"><strong>{user.branch?.code || '—'}</strong><span className="block text-xs text-slate-500">{user.branch?.name || ''}</span></td><td className="p-4"><span className={user.pin_status === 'ACTIVE' ? 'text-emerald-700' : 'text-amber-700'}>{user.pin_status}</span></td><td className="p-4 text-xs text-slate-600">Controlled by this branch's terminal access mode</td></tr>)}{!state.users.length && <tr><td colSpan="5" className="p-10 text-center text-slate-500">No staff records found.</td></tr>}</tbody></table></div>}
    {creating && <div className="fixed inset-0 z-[70] flex items-center justify-center overflow-y-auto bg-black/60 p-4"><form onSubmit={submit} className="my-8 w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-black">Create Staff</h2><p className="text-sm text-slate-500">Creates an Auth-free staff record and a one-time PIN.</p></div><button type="button" onClick={() => setCreating(false)}><X/></button></div><label className="block text-sm font-bold">Full name<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="mt-1 w-full rounded-xl border p-3"/></label><label className="mt-4 block text-sm font-bold">Staff code<input required value={form.staffCode} onChange={event => setForm({ ...form, staffCode: event.target.value.toUpperCase() })} placeholder="e.g. CS001" className="mt-1 w-full rounded-xl border p-3"/></label><label className="mt-4 block text-sm font-bold">Role<select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })} className="mt-1 w-full rounded-xl border p-3">{roles.map(role => <option key={role}>{role}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Branch<select required value={form.branchId} onChange={event => setForm({ ...form, branchId: event.target.value })} className="mt-1 w-full rounded-xl border p-3"><option value="">Select branch</option>{branches.filter(branch => branch.status === 'ACTIVE').map(branch => <option key={branch.id} value={branch.id}>{branch.code} · {branch.name}</option>)}</select></label><p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Terminals in this branch grant access according to their access mode: all branch staff, allowed roles, or explicitly selected staff.</p><div className="mt-6 flex gap-3"><button type="button" onClick={() => setCreating(false)} className="flex-1 rounded-xl border p-3 font-bold">Cancel</button><button disabled={state.busy} className="flex-1 rounded-xl bg-[#D4AF37] p-3 font-black">{state.busy ? 'Creating…' : 'Create Staff'}</button></div></form></div>}
    {temporaryPin && <div className="fixed inset-0 z-[85] flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-xl font-black">Temporary POS PIN</h2><p className="mt-3 text-sm text-slate-600">Give this one-time PIN to the staff member. They must set a permanent PIN after their first terminal sign-in.</p><div className="my-5 rounded-2xl bg-slate-950 p-5 text-center font-mono text-4xl tracking-[0.3em] text-[#D4AF37]">{temporaryPin}</div><button onClick={() => void copy()} className="flex w-full items-center justify-center gap-2 rounded-xl border p-3 font-bold">{copied ? <Check size={18}/> : <Copy size={18}/>} {copied ? 'Copied' : 'Copy PIN'}</button><button onClick={() => { setTemporaryPin(''); setCopied(false); }} className="mt-3 w-full rounded-xl bg-[#D4AF37] p-3 font-black">Done</button></div></div>}
  </section>;
}
