export const POS_CAPABILITIES = Object.freeze({
  START_ORDER: 'START_ORDER',
  VIEW_UNPAID_ORDERS: 'VIEW_UNPAID_ORDERS',
  TAKE_PAYMENT: 'TAKE_PAYMENT',
  OPERATE_KITCHEN: 'OPERATE_KITCHEN',
  SERVE_ORDER: 'SERVE_ORDER',
  VIEW_REPORTS: 'VIEW_REPORTS',
  OPERATE_TABLES: 'OPERATE_TABLES',
  HANDLE_EXCEPTIONS: 'HANDLE_EXCEPTIONS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
});

const roleCapabilities = Object.freeze({
  ADMIN: new Set(Object.values(POS_CAPABILITIES)),
  MANAGER: new Set([
    POS_CAPABILITIES.START_ORDER,
    POS_CAPABILITIES.VIEW_UNPAID_ORDERS,
    POS_CAPABILITIES.TAKE_PAYMENT,
    POS_CAPABILITIES.OPERATE_KITCHEN,
    POS_CAPABILITIES.SERVE_ORDER,
    POS_CAPABILITIES.VIEW_REPORTS,
    POS_CAPABILITIES.OPERATE_TABLES,
    POS_CAPABILITIES.HANDLE_EXCEPTIONS,
  ]),
  CASHIER: new Set([
    POS_CAPABILITIES.START_ORDER,
    POS_CAPABILITIES.VIEW_UNPAID_ORDERS,
    POS_CAPABILITIES.TAKE_PAYMENT,
  ]),
  WAITER: new Set([
    POS_CAPABILITIES.START_ORDER,
    POS_CAPABILITIES.VIEW_UNPAID_ORDERS,
    POS_CAPABILITIES.SERVE_ORDER,
    POS_CAPABILITIES.OPERATE_TABLES,
  ]),
  KITCHEN: new Set([POS_CAPABILITIES.OPERATE_KITCHEN]),
});

export function hasPosCapability(role, capability) {
  return Boolean(roleCapabilities[String(role || '').toUpperCase()]?.has(capability));
}
