import React, { useMemo, useState } from 'react';
import { ArrowDownAZ, ArrowLeft, ChevronLeft, ChevronRight, Download, FileSpreadsheet, FileText, Loader2, PackageSearch, RefreshCw, Search, TrendingUp } from 'lucide-react';
import { REPORT_DEFINITIONS, REPORT_GROUPS } from '../features/reports/config/reportDefinitions';
import { useReport } from '../features/reports/hooks/useReport';
import { formatReportValue } from '../features/reports/utils/reportFormatters';
import { buildReportSummary } from '../features/reports/utils/reportSummary';
import { fetchCompleteReportRows } from '../features/reports/services/reportService';

function isoDate(date) { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 10); }
function presetRange(preset) {
  const now = new Date(); const end = new Date(now); const start = new Date(now);
  if (preset === 'yesterday') { start.setDate(start.getDate() - 1); end.setDate(end.getDate() - 1); }
  if (preset === 'last7') start.setDate(start.getDate() - 6);
  if (preset === 'month') start.setDate(1);
  if (preset === 'lastMonth') { start.setMonth(start.getMonth() - 1, 1); end.setDate(0); }
  return [isoDate(start), isoDate(end)];
}

export default function ReportsScreen({ onBack, embedded = false }) {
  const state = useReport(); const [reportId, setReportId] = useState('daily-sales'); const initial = presetRange('today');
  const [dateFrom, setDateFrom] = useState(initial[0]); const [dateTo, setDateTo] = useState(initial[1]);
  const [exporting, setExporting] = useState(''); const [exportError, setExportError] = useState('');
  const definition = REPORT_DEFINITIONS[reportId];
  const summary = useMemo(() => state.report ? buildReportSummary(state.report.reportId, state.rows, state.report.summary) : [], [state.report, state.rows]);
  const applyPreset = value => { const [from, to] = presetRange(value); setDateFrom(from); setDateTo(to); };
  const exportFile = async type => { if (!state.report) return; setExporting(type); setExportError(''); try { const query = { search: state.search, sortKey: state.sort.key, sortDirection: state.sort.direction }; const rows = await fetchCompleteReportRows(state.report, query); const exportReport = { ...state.report, appliedFilters: query }; if (type === 'pdf') { const {exportReportPdf}=await import('../features/reports/services/pdfExportService');await exportReportPdf(exportReport, rows); } else { const {exportReportExcel}=await import('../features/reports/services/excelExportService');await exportReportExcel(exportReport, rows); } } catch (error) { console.error('Report export failed', error); setExportError(`Unable to export ${type.toUpperCase()}.`); } finally { setExporting(''); } };
  return <div className={`${embedded ? '' : 'h-full overflow-y-auto bg-slate-50 p-3 sm:p-6'} text-slate-950`}>
    <header className="mb-4 flex flex-wrap items-start justify-between gap-3 sm:mb-5">{!embedded&&<button onClick={onBack} aria-label="Back" className="rounded-xl border bg-white p-3"><ArrowLeft/></button>}<div className="min-w-0 flex-1"><h1 className="flex items-center gap-2 text-xl font-black sm:text-2xl"><TrendingUp className="shrink-0 text-amber-600"/>Reports</h1><p className="text-xs text-slate-500 sm:text-sm">Generate, review, then export database-backed operational and financial reports.</p></div>{state.report&&<button onClick={()=>state.run(reportId,dateFrom,dateTo)} className="rounded-xl border bg-white p-3" title="Regenerate" aria-label="Regenerate report"><RefreshCw size={17}/></button>}</header>
    <div className="grid gap-4 xl:grid-cols-[260px_1fr] xl:gap-5">
      <aside className="rounded-2xl border bg-white p-2 shadow-sm xl:sticky xl:top-3 xl:h-fit xl:p-3">{REPORT_GROUPS.map(group=><section key={group.id} className="mb-3 last:mb-0"><h2 className="px-2 pb-1 text-[10px] font-black uppercase tracking-widest text-slate-400">{group.label}</h2><div className="flex gap-1 overflow-x-auto pb-1 xl:block">{group.reports.map(id=><button key={id} onClick={()=>setReportId(id)} className={`mb-1 shrink-0 rounded-xl px-3 py-2.5 text-left text-xs font-bold xl:block xl:w-full sm:text-sm ${reportId===id?'bg-slate-950 text-amber-400':'hover:bg-slate-50'}`}>{REPORT_DEFINITIONS[id].title}</button>)}</div></section>)}</aside>
      <main className="space-y-5">
        <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4"><p className="text-xs font-black uppercase text-amber-700">Selected report</p><h2 className="text-xl font-black">{definition.title}</h2></div><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-bold">Quick range<select onChange={e=>applyPreset(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last7">Last 7 Days</option><option value="month">This Month</option><option value="lastMonth">Last Month</option></select></label><label className="text-xs font-bold">From<input type="date" value={dateFrom} max={dateTo} onChange={e=>setDateFrom(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2"/></label><label className="text-xs font-bold">To<input type="date" value={dateTo} min={dateFrom} onChange={e=>setDateTo(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2"/></label><button disabled={state.loading} onClick={()=>state.run(reportId,dateFrom,dateTo)} className="rounded-xl bg-amber-400 px-6 py-2.5 font-black disabled:opacity-50">{state.loading?'Generating…':'Generate Preview'}</button></div></section>
        {(state.error||exportError)&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{state.error||exportError}</div>}
        {state.loading?<div className="flex justify-center gap-2 rounded-2xl border bg-white p-14 text-slate-500"><Loader2 className="animate-spin"/>Loading report…</div>:state.report&&<>
          <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-black uppercase text-amber-700">Preview</p><h2 className="text-xl font-black">{state.report.definition.title}</h2><p className="mt-1 text-xs text-slate-500">Period: {state.report.dateFrom} – {state.report.dateTo} · Generated {new Date(state.report.generatedAt).toLocaleString()} by {state.report.generatedBy}</p></div><div className="flex gap-2"><button disabled={Boolean(exporting)} onClick={()=>exportFile('pdf')} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-50"><FileText size={16}/>{exporting==='pdf'?'Exporting…':'Export PDF'}</button><button disabled={Boolean(exporting)} onClick={()=>exportFile('excel')} className="flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><FileSpreadsheet size={16}/>{exporting==='excel'?'Exporting…':'Export Excel'}</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{summary.map(item=><div key={item.label} className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase text-slate-400">{item.label}</p><strong className="mt-1 block text-xl">{formatReportValue(item.value,item.type)}</strong></div>)}</div></section>
          <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b p-4"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={state.search} onChange={e=>state.setSearch(e.target.value)} placeholder="Search this generated report" className="w-full rounded-xl border py-2.5 pl-10"/></div><label className="text-xs font-bold">Rows <select value={state.pageSize} onChange={e=>state.setPageSize(Number(e.target.value))} className="ml-1 rounded-lg border p-2"><option>25</option><option>50</option><option>100</option></select></label><span className="flex items-center gap-1 text-xs text-slate-400"><Download size={14}/>{state.total} matching rows</span></div>
          {state.rows.length===0?<div className="p-12 text-center text-slate-500"><PackageSearch className="mx-auto mb-3"/>No transactions found for the selected period.<p className="text-xs">Try changing the date range or search.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-max text-sm"><thead className="bg-slate-100 text-left text-[10px] uppercase text-slate-500"><tr>{state.report.definition.columns.map(column=><th key={column.key} className="p-3"><button onClick={()=>state.toggleSort(column.key)} className="flex items-center gap-1 font-black">{column.label}<ArrowDownAZ size={12}/></button></th>)}</tr></thead><tbody>{state.visibleRows.map((row,index)=><tr key={row.id||row.order_id||row.payment_id||`${state.page}-${index}`} className="border-t hover:bg-amber-50">{state.report.definition.columns.map(column=><td key={column.key} className={`max-w-xs p-3 ${['currency','number','percent'].includes(column.type)?'text-right':''}`}>{formatReportValue(row[column.key],column.type)}</td>)}</tr>)}</tbody></table></div>}
          <div className="flex items-center justify-between border-t p-4 text-xs"><span>Showing {state.total?((state.page-1)*state.pageSize)+1:0}–{Math.min(state.page*state.pageSize,state.total)} of {state.total}</span><div className="flex items-center gap-2"><button disabled={state.page<=1} onClick={()=>state.setPage(state.page-1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft size={15}/></button><strong>Page {state.page} of {state.pageCount}</strong><button disabled={state.page>=state.pageCount} onClick={()=>state.setPage(state.page+1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight size={15}/></button></div></div></section>
        </>}
      </main>
    </div>
  </div>;
}
