alter table public.pos_terminals add column if not exists terminal_type text not null default 'POS' check(terminal_type in ('POS','KDS'));
alter table public.pos_terminals add column if not exists registration_status text not null default 'REGISTERED' check(registration_status in ('REGISTERED','UNREGISTERED','REVOKED'));
alter table public.pos_terminals add column if not exists device_identifier text;
alter table public.pos_terminals add column if not exists registered_at timestamptz;
alter table public.pos_terminals add column if not exists registered_by uuid references public.profiles(id) on delete set null;
alter table public.pos_terminals add column if not exists last_seen_at timestamptz;
create index if not exists pos_terminals_device_idx on public.pos_terminals(device_identifier) where device_identifier is not null;
create or replace function public.save_pos_terminal(p_id uuid,p_branch_id uuid,p_code text,p_name text,p_status text default 'ACTIVE',p_type text default 'POS',p_device_identifier text default null) returns public.pos_terminals language plpgsql security definer set search_path=public as $$ declare r public.pos_terminals; begin if not public.has_pos_permission('settings.manage') then raise exception 'INSUFFICIENT_PERMISSION'; end if; if not exists(select 1 from public.branches where id=p_branch_id and status='ACTIVE') then raise exception 'INVALID_BRANCH'; end if; insert into public.pos_terminals(id,branch_id,terminal_code,name,status,terminal_type,device_identifier,registration_status,registered_at,registered_by) values(coalesce(p_id,gen_random_uuid()),p_branch_id,upper(trim(p_code)),trim(p_name),upper(p_status),upper(p_type),nullif(trim(p_device_identifier),''),'REGISTERED',now(),auth.uid()) on conflict(id) do update set branch_id=excluded.branch_id,terminal_code=excluded.terminal_code,name=excluded.name,status=excluded.status,terminal_type=excluded.terminal_type,device_identifier=excluded.device_identifier,updated_at=now() returning * into r; return r; end $$;
grant execute on function public.save_pos_terminal(uuid,uuid,text,text,text,text,text) to authenticated;
