create table if not exists public.terminal_staff_sessions (
 id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete restrict, branch_id uuid not null references public.branches(id) on delete restrict, terminal_id uuid not null references public.pos_terminals(id) on delete restrict, staff_id uuid not null references public.profiles(id) on delete restrict, status text not null default 'ACTIVE' check(status in ('ACTIVE','LOCKED','ENDED')), started_at timestamptz not null default now(), last_activity_at timestamptz not null default now(), ended_at timestamptz
);
create unique index if not exists one_active_terminal_staff_session on public.terminal_staff_sessions(terminal_id) where status in ('ACTIVE','LOCKED');
create index if not exists terminal_staff_sessions_staff_idx on public.terminal_staff_sessions(staff_id,status);
alter table public.terminal_staff_sessions enable row level security;
create policy terminal_staff_session_read on public.terminal_staff_sessions for select to authenticated using(public.has_pos_permission('user.view') or staff_id=auth.uid());
create or replace function public.resolve_registered_terminal(p_device_identifier text) returns jsonb language plpgsql security definer set search_path=public as $$ declare t public.pos_terminals%rowtype; b public.branches%rowtype; c public.companies%rowtype; begin select * into t from public.pos_terminals where device_identifier=p_device_identifier; if not found then return jsonb_build_object('ok',false,'code','TERMINAL_NOT_REGISTERED'); end if; select * into b from public.branches where id=t.branch_id; select * into c from public.companies where id=b.company_id; if t.status<>'ACTIVE' then return jsonb_build_object('ok',false,'code','TERMINAL_INACTIVE'); end if; if t.registration_status<>'REGISTERED' then return jsonb_build_object('ok',false,'code','TERMINAL_NOT_REGISTERED'); end if; if b.status<>'ACTIVE' then return jsonb_build_object('ok',false,'code','BRANCH_INACTIVE'); end if; if c.status<>'ACTIVE' then return jsonb_build_object('ok',false,'code','COMPANY_INACTIVE'); end if; update public.pos_terminals set last_seen_at=now() where id=t.id; return jsonb_build_object('ok',true,'companyId',c.id,'companyName',c.name,'branchId',b.id,'branchCode',b.code,'terminalId',t.id,'terminalCode',t.terminal_code,'terminalName',t.name,'terminalType',t.terminal_type); end $$;
create or replace function public.list_terminal_branch_staff(p_device_identifier text) returns setof public.profiles language plpgsql security definer set search_path=public as $$ declare t public.pos_terminals%rowtype; begin select * into t from public.pos_terminals where device_identifier=p_device_identifier and status='ACTIVE' and registration_status='REGISTERED'; if not found then raise exception 'TERMINAL_INVALID'; end if; return query select p.* from public.profiles p where p.branch_id=t.branch_id and p.status='ACTIVE' and p.role_name in ('MANAGER','WAITER','CASHIER','KITCHEN','ADMIN') order by p.name; end $$;
grant execute on function public.resolve_registered_terminal(text),public.list_terminal_branch_staff(text) to authenticated;
