import React from 'react';
import { AlertTriangle, Clock3, Database, Radio, RefreshCw, Server, ShieldAlert, Wifi } from 'lucide-react';
import type { HealthCheck, SystemHealth } from '../../types/systemHealth';
import { HealthBadge } from '../../components/system-health/HealthBadge';

const dateTime=(value?:string)=>value?new Intl.DateTimeFormat('en-MY',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Kuala_Lumpur'}).format(new Date(value)):'—';
const ago=(value?:string)=>{if(!value)return'never';const seconds=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/1000));return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago`;};
const iconFor=(component:string)=>component==='database'?Database:component==='realtime'?Radio:component.includes('api')||component.includes('edge')?Server:component==='supabase'?Wifi:component==='backup'?Clock3:ShieldAlert;

function HealthCard({check}:{check:HealthCheck}){const Icon=iconFor(check.component);const subchecks=Array.isArray(check.metadata?.checks)?check.metadata.checks as HealthCheck[]:[];return <article title={`${check.label} — ${check.status}. ${check.message}`} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="rounded-xl bg-slate-100 p-2 text-slate-600"><Icon size={19}/></span><HealthBadge status={check.status} label={check.operationalStatus}/></div><h2 className="mt-3 font-black text-slate-950">{check.label}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-slate-500">{check.message}</p><div className="mt-3 flex flex-wrap gap-x-3 text-[10px] font-bold text-slate-400">{check.latencyMs!==undefined&&<span>{check.latencyMs} ms</span>}<span>Checked {ago(check.lastCheckedAt)}</span></div>{subchecks.length>0&&<div className="mt-3 space-y-1 border-t pt-3">{subchecks.map(item=><div key={item.component} className="flex items-center justify-between text-xs"><span>{item.label} <small className="text-slate-400">{item.latencyMs} ms</small></span><HealthBadge status={item.status}/></div>)}</div>}</article>}

export default function SystemHealthPage({state}:{state:{data:SystemHealth|null;isLoading:boolean;isRefreshing:boolean;error:string;refresh:()=>Promise<void>}}){
  const {data}=state;
  if(state.isLoading&&!data)return <div className="space-y-4 animate-pulse"><div className="h-44 rounded-3xl bg-slate-200"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-48 rounded-2xl bg-slate-200"/>)}</div></div>;
  if(!data)return <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h1 className="font-black">Health Dashboard Unavailable</h1><p className="mt-2 text-sm">{state.error||'The monitoring service could not be reached. Core POS operations remain independent.'}</p><button onClick={()=>void state.refresh()} className="mt-4 rounded-xl bg-red-700 px-4 py-2 text-sm font-bold text-white">Retry</button></div>;
  const urgent=data.components.filter(item=>item.status==='CRITICAL'||item.status==='WARNING');
  return <section className="space-y-5"><header className={`rounded-3xl p-6 text-white ${data.overallStatus==='CRITICAL'?'bg-red-800':data.overallStatus==='WARNING'?'bg-amber-700':data.overallStatus==='DEGRADED'?'bg-orange-700':data.overallStatus==='HEALTHY'?'bg-emerald-800':'bg-slate-700'}`}><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black tracking-[0.25em] opacity-80">SYSTEM HEALTH</p><div className="mt-3 flex items-center gap-3"><h1 className="text-3xl font-black">{data.overallStatus}</h1><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-black">{data.environment}</span></div><p className="mt-3 text-sm opacity-80">Last checked {dateTime(data.checkedAt)}</p></div><button disabled={state.isRefreshing} onClick={()=>void state.refresh()} className="flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-black text-slate-900 disabled:opacity-60"><RefreshCw size={16} className={state.isRefreshing?'animate-spin':''}/>{state.isRefreshing?'Checking…':'Refresh Health'}</button></div><div className="mt-5 flex flex-wrap gap-4 border-t border-white/20 pt-4 text-xs"><span>Application <strong>{data.version.appVersion}</strong></span><span>Commit <strong>{data.version.commitSha?.slice(0,8)||'not injected'}</strong></span><span>Build <strong>{data.version.buildId||'not injected'}</strong></span><span>Correlation <strong>{data.correlationId}</strong></span></div></header>
    {state.error&&<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Refresh failed: {state.error}. Showing the last successful snapshot.</div>}
    <div className="rounded-2xl border bg-white p-4"><h2 className="flex items-center gap-2 text-sm font-black"><AlertTriangle size={17} className={urgent.length?'text-amber-600':'text-emerald-600'}/>What to investigate first</h2>{urgent.length?<ol className="mt-3 space-y-2">{urgent.map(item=><li key={item.component} className="flex gap-2 text-sm"><HealthBadge status={item.status}/><span><strong>{item.label}:</strong> {item.message}</span></li>)}</ol>:<p className="mt-2 text-sm text-slate-500">No warning or critical checks are active. Unknown components still require integration before they can be asserted healthy.</p>}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.components.map(check=><HealthCard key={check.component} check={check}/>)}</div>
    <div className="grid gap-5 xl:grid-cols-3"><section className="rounded-2xl border bg-white p-5 xl:col-span-1"><h2 className="font-black">Failed API Calls — 24 Hours</h2><div className="mt-4 grid grid-cols-2 gap-2 text-center">{[['Requests',data.api.totalRequests],['Failures',data.api.failedRequests],['5xx',data.api.serverErrors],['Timeouts',data.api.timeouts]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><strong className="block text-xl">{value}</strong><span className="text-[10px] uppercase text-slate-500">{label}</span></div>)}</div><p className="mt-3 text-xs text-slate-500">Infrastructure failure rate: <strong>{(data.api.failureRate*100).toFixed(2)}%</strong> · 4xx observed: {data.api.clientErrors}</p></section><section className="overflow-hidden rounded-2xl border bg-white p-5 xl:col-span-2"><h2 className="font-black">Recent API Errors</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b text-left uppercase text-slate-400">{['Time','Service','Endpoint','Method','Status','Error','Duration','Correlation ID'].map(x=><th key={x} className="px-2 py-2">{x}</th>)}</tr></thead><tbody>{data.api.recentErrors.map((event,index)=><tr key={`${event.correlation_id}-${index}`} className="border-b"><td className="px-2 py-2">{dateTime(event.occurred_at)}</td><td className="px-2">{event.service}</td><td className="px-2 font-mono">{event.endpoint}</td><td className="px-2">{event.method}</td><td className="px-2">{event.status_code||'—'}</td><td className="px-2">{event.error_type||'—'}</td><td className="px-2">{event.duration_ms??'—'} ms</td><td className="px-2 font-mono">{event.correlation_id}</td></tr>)}</tbody></table>{!data.api.recentErrors.length&&<p className="py-8 text-center text-sm text-slate-400">No error telemetry recorded in this window.</p>}</div></section></div>
    <section className="overflow-hidden rounded-2xl border bg-white p-5"><h2 className="font-black">Recent System Incidents</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400">{['Opened','Severity','Component','Error','Status','Correlation ID'].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody>{data.incidents.map(item=><tr key={item.id} className="border-b"><td className="px-3 py-3">{dateTime(item.opened_at)}</td><td className="px-3"><span className="font-black">{item.severity}</span></td><td className="px-3">{item.component}</td><td className="px-3">{item.summary}</td><td className="px-3">{item.status}</td><td className="px-3 font-mono text-xs">{item.correlation_id||'—'}</td></tr>)}</tbody></table>{!data.incidents.length&&<p className="py-8 text-center text-sm text-slate-400">No incidents have been recorded.</p>}</div></section>
  </section>;
}
